### ISSUE TITLE
crm_text() parameter for adding a browser useragent string?

### ISSUE THREAD

**Issue by sckott** [ropensci/crminer#42]
via #41

**Comment by sckott** [comment]
potentially make it a random string every time

**Comment by mark-fangzhou-xie** [comment]
I am not sure changing user-agent string frequently is a good idea. 

Though I am not sure what is the mechanism behind publishers' server (for detecting user agents), in general web scrapping practices, changing user agent frequently but leaving ip address unchanged will stand out immediately. The website could detect you very easily, just because you are changing user-agents. For example, a person who is surfing online will most likely use his/her favorite browser and stick to it, therefore using the same user-agent string within a certain period of time; while a scrapper, with constantly changing user-agents, will behave like a person who uses tens/hundreds of different browsers to visit the same website. That could be very suspicious and the website will know you are a program immediately.

In our case, one of our hands is tied (as we can't change ip address) and we would probably be better off just supplying a user-agent string and stick to it, instead of changing it from time to time. If the publishers' website is only using regex to search for the presence of user-agent strings, we will be fine either way; if they indeed employ some anormaly-detection algorithm, which I highly doubt would be the case as I observe in the verbose logs of some requests are made through `cloudflare` (a web security company who fight against scrappers), we would be immediately noticed by their service.

**Comment by mark-fangzhou-xie** [comment]
That said, we do want the user-agent string to be provided dynamically. User-agent strings are updated as the browsers are updating, and if we supply some very outdated user-agent user-agent string, that will be a red flag as well.

**Comment by sckott** [comment]
Okay, good points. 

I ended up not adding a parameter, but instead documenting useragent strings in some detail with a new section in fxns crm_text/_pdf/_plain/_xml/_html
